Ease using regipy as a library
mkorman90/regipy pull request #174
Opened 2021-07-13 07:25 UTC by pombredanne

This PR resolves #171 and #172:
- #171 replace logbook by the standard library logging
- #172 make some deps optional with an extra_requires for [cli] to ease use as a library

It also removes the jsonlines dependency and uses instead the standard library `json` module to the same effect.

It makes also some minor extra changes such as:
- escaping a regex
- marking Python 3.6 and 3.9 as supported
- minor documentation adjustments

Signed-off-by: Philippe Ombredanne <pombredanne@nexb.com>

2021-07-14 09:16 UTC, tincho9 reviewed
Thanks, I really like this solution.

2021-07-14 12:47 UTC, pombredanne commented
@tincho9 ready to merge IMHO :)

2021-07-18 07:00 UTC, tincho9 requested changes
I would like to move back the import to outside the plugin run function.

2021-07-18 09:27 UTC, pombredanne commented on regipy/plugins/software/last_logon.py
> +        from inflection import underscore
I can move that out... that's used anyway. It has no impact here to have a method-private vs. a top level import.

2021-07-18 10:20 UTC, tincho9 commented on regipy/plugins/software/last_logon.py
> +        from inflection import underscore
I just think the code is clearer that way :)

2021-07-18 12:37 UTC, tincho9 approved these changes

2021-07-18 12:42 UTC, pombredanne commented on regipy/plugins/software/last_logon.py
> +        from inflection import underscore
The latest push restored the original imports

2021-07-18 12:53 UTC, tincho9 commented
Looks great now! I think we should bump the version to 2.0.0, since it is a bit of a breaking change for people that use the CLI. After that change we can merge.

2021-07-18 15:41 UTC, pombredanne commented
> Looks great now! I think we should bump the version to 2.0.0, since it is a bit of a breaking change for people that use the CLI. After that change we can merge.

Alternatively there could be two packages built:
- `regipy` which has the same set of deps as today
-  `regipy-lib` which a minimal deps for library usage which is a bit more involved as the build scripts needs to be special to handle this

2021-07-19 06:55 UTC, merged

2021-07-19 08:26 UTC, pombredanne commented
@tincho9 thank you ++ :bow: