Add support for the `SECURITY` hive type
mkorman90/regipy pull request #182
Opened 2021-07-23 05:58 UTC by ravenexp

1. Adds a new hive type and updates the auto-detection routine.
1. Adds a binary SID decoding utility function.
1. Adds a sample plugin that operates on the newly supported `SECURITY` hive.

2021-07-25 06:34 UTC, tincho9 requested changes
Looks great! Can you please add a test?

2021-07-25 07:10 UTC, ravenexp commented
Yes, I thought about doing that. The problem is I didn't have a suitable registry hive file I could add to the test data. I tested the code on the real Windows machine `SECURITY` hive, but I couldn't just upload it because it's full of security-sensitive info.

Perhaps you could suggest me a good way of creating such a test file, because I couldn't think of any. Even if I do a clean VM install, I can't join this machine to an AD domain because I don't have administrator permissions in any domains. And the `domain_sid` plugin depends on the machine being joined to a domain.

2021-07-29 08:35 UTC, tincho9 approved these changes
Lets leave it without a test then

2021-07-29 08:35 UTC, tincho9 commented on regipy/utils.py
> +        raise ValueError("Unexpected SID component count")
Please inherit from `RegipyException`

2021-07-30 09:08 UTC, ravenexp commented on regipy/utils.py
> +        raise ValueError("Unexpected SID component count")
I've added `NtSidDecodingException(RegipyException)`  class.

2021-08-02 12:53 UTC, merged