shell bug pull request
mkorman90/regipy pull request #223
Opened 2022-06-06 14:04 UTC by tomerlahiyani

2022-06-07 06:11 UTC, mkorman90 requested changes
Looks great! Only requiring some minor changes. 

Also, do not forget to add `libfwsi-python==20210419 ` as a dependency in `requirements.txt`

2022-06-07 06:11 UTC, mkorman90 commented on regipy/plugins/ntuser/shellbags_ntuser.py
> +            item_type = 'UNKOWN'
```suggestion
            item_type = 'unknown'
```

2022-06-07 06:11 UTC, mkorman90 commented on regipy/plugins/ntuser/shellbags_ntuser.py
> +        if path_segment is None and shell_item.class_type == 0x00:
Why are you checking this condition if you are not doing anything with it?

2022-06-07 06:11 UTC, mkorman90 commented on regipy/plugins/ntuser/shellbags_ntuser.py
> +                        modification_time = ''
```suggestion
                        modification_time = None
```

2022-06-07 06:11 UTC, mkorman90 commented on regipy/plugins/ntuser/shellbags_ntuser.py
> +        """
Delete commented lines

2022-06-07 06:11 UTC, mkorman90 commented on regipy_tests/plugin_tests.py
> +import datetime
datetime is usually (as a convention) imported as:
```
import datetime as dt
```

and then used like this: 
```
 dt.datetime(2021, 8, 16, 9, 43, 22).isoformat()
```

2022-06-08 05:17 UTC, mkorman90 approved these changes

2022-06-08 08:49 UTC, mkorman90 approved these changes

2022-06-08 08:51 UTC, mkorman90 approved these changes

2022-06-08 08:57 UTC, merged

2022-06-09 06:54 UTC, SMillerDev commented
It seems this change missed `setup.py` for the new dependency. So anything using that for dependencies (e.g Homebrew) now needs to add it manually.