add trim_values support
mkorman90/regipy pull request #245
Opened 2023-02-08 18:18 UTC by menimensygnia

2023-02-11 10:14 UTC, mkorman90 requested changes

2023-02-20 07:35 UTC, yuvalmarciano commented on regipy/plugins/plugin.py
> +    def __init__(self, registry_hive: RegistryHive, as_json=False, trim_values=True):
```suggestion
    def __init__(self, registry_hive: RegistryHive, as_json=False, trim_values=False):
```

2023-02-20 07:35 UTC, yuvalmarciano commented on regipy/registry.py
> +    def get_values(self, as_json=False, trim_values=True):
```suggestion
    def get_values(self, as_json=False, trim_values=False):
```

2023-02-21 13:48 UTC, mkorman90 approved these changes

2023-02-21 13:51 UTC, closed without merging